name: Build a beta

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create and Push Tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +'%Y%m%d-%H%M')
          TAG="v$VERSION-$DATE"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag $TAG
          git push origin $TAG

      - name: Install deps
        run: npm install --legacy-peer-deps || true

      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean

      - name: Configure Gradle
        run: |
          chmod +x android/gradlew
          echo "org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError" >> android/gradle.properties
          echo "android.enable16KbPageSizes=true" >> android/gradle.properties

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/*.apk