name: iOS Build (Unsigned IPA)

on:
  workflow_dispatch:

jobs:
  ios:
    runs-on: xcode-27

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          package-manager-cache: false

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check Expo
        run: |
          npx expo --version
          node -p "require('./node_modules/expo/package.json').version"

      - name: Expo prebuild iOS
        run: npx expo prebuild --platform ios --clean

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Show Xcode information
        run: |
          xcodebuild -version
          xcodebuild -workspace ios/Papillon.xcworkspace -list

      - name: Archive iOS app
        run: |
          xcodebuild archive \
            -workspace ios/Papillon.xcworkspace \
            -scheme Papillon \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath ios/build/Papillon.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            SKIP_INSTALL=NO

      - name: Create IPA
        run: |
          mkdir -p ios/build/Payload
          cp -R ios/build/Papillon.xcarchive/Products/Applications/Papillon.app \
                ios/build/Payload/

          cd ios/build
          zip -r Papillon.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Papillon-unsigned-IPA
          path: ios/build/Papillon.ipa
